version: "3.9"
services:
  webapp_migrations:
    image: registry.gitlab.com/nishirken/calendar-api:${TAG_MIGRATIONS}
    env_file: .env
    depends_on:
      - postgres

  webapp: 
    image: registry.gitlab.com/nishirken/calendar-api:${TAG_APP}
    ports:
      - 127.0.0.1:8081:8081
    env_file: .env
    depends_on:
      - webapp_migrations
      - postgres

  postgres:
    image: docker.io/library/postgres:14
    expose:
      - "5555"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file: .env
    command:
      - "-p 5555"
