name: "Deploy"

on:
  workflow_dispatch:
    inputs:
      migrations:
        type: boolean
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-22.11
          extra_nix_config: |
            substituters = https://cache.iog.io https://cache.nixos.org https://nix-community.cachix.org https://nishirken-calendar-api-ci.cachix.org
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nishirken-calendar-api-ci.cachix.org-1:nOxlonOnNb+S7SEIouJXiOjRasq4opMzxSVNYB2HB7k=

      - uses: cachix/cachix-action@v12
        with:
          name: nishirken-calendar-api-ci
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: "Build migrations"
        if: "${{ github.event.inputs.migrations == 'true' }}"
        run: nix build .#calendar-api:exe:calendar-api-migrations --print-out-paths

      - name: "Build"
        run: nix build . --print-out-paths
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GANDI_CALENDAR_USERNAME }}
      HOST: ${{ secrets.GANDI_CALENDAR_HOST }}
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.GANDI_CALENDAR_PRIVATE_KEY }}
         name: "gandi_key"
         known_hosts: ${{ secrets.GANDI_CALENDAR_KNOWN_HOSTS }}
 
      - uses: cachix/install-nix-action@v18
        with:
           nix_path: nixpkgs=channel:nixos-22.11
           extra_nix_config: |
             system-features = benchmark big-parallel nixos-test kvm
             substituters = https://cache.iog.io https://cache.nixos.org https://nix-community.cachix.org https://nishirken-calendar-api-ci.cachix.org
             trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nishirken-calendar-api-ci.cachix.org-1:nOxlonOnNb+S7SEIouJXiOjRasq4opMzxSVNYB2HB7k=
 
      - uses: redhat-actions/podman-login@v1.5
        with:
          username: nishirken
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          registry: registry.gitlab.com/nishirken/calendar-api

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Set env"
        run: |
          echo "TAG_APP=app_$(date +%s)" >> $GITHUB_ENV # timestamp
          echo "TAG_MIGRATIONS=migrations_$(date +%s)" >> $GITHUB_ENV # timestamp

      - name: "Build migrations image"
        if: "${{ github.event.inputs.migrations == 'true' }}"
        run: |
          podman load < $(nix-build ci/dockerfile-migrations.nix)
          podman push localhost/webapp_migrations:${TAG_MIGRATIONS} registry.gitlab.com/nishirken/calendar-api:${TAG_MIGRATIONS}

      - name: "Build image"
        run: |
          podman load < $(nix-build ci/dockerfile.nix)
          podman push localhost/webapp:${TAG_APP} registry.gitlab.com/nishirken/calendar-api:${TAG_APP}

      - name: "Gen env and config"
        env:
          KEY: ${{ secrets.AUTH_KEY }}
          PASS: ${{ secrets.DB_PASSWORD }}
        run: ./.github/scripts/gen_env.sh

      - name: "Deploy env migrations"
        if: "${{ github.event.inputs.migrations == 'true' }}"
        run: echo "COMPOSE_FILE=docker-compose-migrations.yaml" >> $GITHUB_ENV

      - name: "Deploy env"
        if: "${{ github.event.inputs.migrations == 'false' }}"
        run: echo "COMPOSE_FILE=docker-compose.yaml" >> $GITHUB_ENV
 
      - name: "Start image"
        env:
          TOKEN: ${{ secrets.GANDI_PODMAN_TOKEN }}
        run: node .github/scripts/start_image.js
