name: "Deploy"

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GANDI_CALENDAR_USERNAME }}
      HOST: ${{ secrets.GANDI_CALENDAR_HOST }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          extra_nix_config: |
            substituters = https://hydra.iohk.io https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GANDI_CALENDAR_PRIVATE_KEY }}
          name: "gandi_key"
          known_hosts: ${{ secrets.GANDI_CALENDAR_KNOWN_HOSTS }}

      - uses: redhat-actions/podman-login@v1.4
        with:
          username: nishirken
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          registry: registry.gitlab.com/nishirken/calendar-api

      - name: "Get current time"
        uses: josStorer/get-current-time@v2.0.1
        id: current-time
        with:
          format: X # timestamp

      - name: "Cabal cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-calendar-api-${{ github.ref_name }}
          restore-keys: ${{ runner.os }}-calendar-api-

      - name: "Build"
        env:
          TAG: ${{ steps.current-time.outputs.formattedTime }}
        run: |
          podman load < $(nix-build ci/dockerfile.nix) -q
          podman push localhost/webapp:${TAG} registry.gitlab.com/nishirken/calendar-api:${TAG}

      - name: "Load Image"
        env:
          TAG: ${{ steps.current-time.outputs.formattedTime }}
        run: |
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST mkdir -p /var/calendar-api
          scp -i ~/.ssh/gandi_key ci/docker-compose.yaml $USERNAME@$HOST:/var/calendar-api/docker-compose.yaml
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST podman login registry.gitlab.com/nishirken/calendar-api --username nishirken --password ${{ secrets.GANDI_PODMAN_TOKEN }}
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST TAG=$TAG podman-compose -f /var/calendar-api/docker-compose.yaml up -d --force-recreate

