name: "Deploy"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-22.05
          extra_nix_config: |
            substituters = https://hydra.iohk.io https://cache.nixos.org https://nix-community.cachix.org https://nishirken-calendar-api-ci.cachix.org
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nishirken-calendar-api-ci.cachix.org-1:nOxlonOnNb+S7SEIouJXiOjRasq4opMzxSVNYB2HB7k=

      - uses: cachix/cachix-action@v10
        with:
          name: nishirken-calendar-api-ci
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: "Build"
        run: |
          nix build . --json | jq '.[].outputs.out'
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.GANDI_CALENDAR_USERNAME }}
      HOST: ${{ secrets.GANDI_CALENDAR_HOST }}
    steps:
      - uses: actions/checkout@v3

      - uses: shimataro/ssh-key-action@v2
        with:
         key: ${{ secrets.GANDI_CALENDAR_PRIVATE_KEY }}
         name: "gandi_key"
         known_hosts: ${{ secrets.GANDI_CALENDAR_KNOWN_HOSTS }}
 
      - uses: cachix/install-nix-action@v15
        with:
           nix_path: nixpkgs=channel:nixos-22.05
           extra_nix_config: |
             substituters = https://hydra.iohk.io https://cache.nixos.org https://nix-community.cachix.org https://nishirken-calendar-api-ci.cachix.org
             trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= nishirken-calendar-api-ci.cachix.org-1:nOxlonOnNb+S7SEIouJXiOjRasq4opMzxSVNYB2HB7k=
    
      - uses: redhat-actions/podman-login@v1.4
        with:
          username: nishirken
          password: ${{ secrets.GITLAB_REGISTRY_TOKEN }}
          registry: registry.gitlab.com/nishirken/calendar-api

      - name: "Set env"
        run: echo "TAG=$(date +%s)" >> $GITHUB_ENV # timestamp

      - name: "Build image"
        run: |
          $(nix-build ci/dockerfile.nix) | podman load
          podman push localhost/webapp:${TAG} registry.gitlab.com/nishirken/calendar-api:${TAG}
 
      - name: "Start image"
        run: |
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST mkdir -p /var/calendar-api
          scp -i ~/.ssh/gandi_key ci/docker-compose.yaml $USERNAME@$HOST:/var/calendar-api/docker-compose.yaml
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST podman login registry.gitlab.com/nishirken/calendar-api --username nishirken --password ${{ secrets.GANDI_PODMAN_TOKEN }}
          ssh -i ~/.ssh/gandi_key $USERNAME@$HOST TAG=$TAG podman-compose -f /var/calendar-api/docker-compose.yaml up -d --force-recreate

